"""Updated schema

Revision ID: 23849364c126
Revises: baed9ea76103
Create Date: 2025-04-04 18:44:04.618847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23849364c126'
down_revision: Union[str, None] = 'baed9ea76103'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_start', sa.DateTime(), nullable=False))
    op.add_column('events', sa.Column('event_end', sa.DateTime(), nullable=False))
    op.add_column('events', sa.Column('location', sa.String(length=200), nullable=False))
    op.drop_column('events', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('events', 'location')
    op.drop_column('events', 'event_end')
    op.drop_column('events', 'event_start')
    # ### end Alembic commands ###
