"""Updated schema for users profile

Revision ID: 48450ed9f449
Revises: aa8ff0562c47
Create Date: 2025-04-16 15:03:13.083641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48450ed9f449'
down_revision: Union[str, None] = 'aa8ff0562c47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_feedback_id', table_name='feedback')
    op.drop_table('feedback')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('giver_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('receiver_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('feedback_text', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['giver_user_id'], ['user_profiles.id'], name='feedback_giver_user_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receiver_user_id'], ['user_profiles.id'], name='feedback_receiver_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='feedback_pkey')
    )
    op.create_index('ix_feedback_id', 'feedback', ['id'], unique=False)
    # ### end Alembic commands ###
