"""Fix migrations

Revision ID: 5d71b82de3b8
Revises: a38fadc56c60
Create Date: 2025-04-04 00:05:38.837219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d71b82de3b8'
down_revision: Union[str, None] = 'a38fadc56c60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('options')
    op.drop_table('questions')
    op.drop_table('events')
    op.drop_constraint('auth_users_room_number_residence_hall_id_fkey', 'auth_users', type_='foreignkey')
    op.drop_column('auth_users', 'residence_hall_id')
    op.drop_column('auth_users', 'room_number')
    op.add_column('user_profiles', sa.Column('room_number', sa.Integer(), nullable=True))
    op.add_column('user_profiles', sa.Column('residence_hall_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_profiles', 'rooms', ['room_number', 'residence_hall_id'], ['room_number', 'residence_hall_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profiles', type_='foreignkey')
    op.drop_column('user_profiles', 'residence_hall_id')
    op.drop_column('user_profiles', 'room_number')
    op.add_column('auth_users', sa.Column('room_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('auth_users', sa.Column('residence_hall_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('auth_users_room_number_residence_hall_id_fkey', 'auth_users', 'rooms', ['room_number', 'residence_hall_id'], ['room_number', 'residence_hall_id'], ondelete='SET NULL')
    op.create_table('events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('approved_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('requested_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['auth_users.id'], name='events_approved_by_fkey'),
    sa.ForeignKeyConstraint(['requested_by'], ['auth_users.id'], name='events_requested_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='events_pkey'),
    sa.UniqueConstraint('title', name='events_title_key')
    )
    op.create_table('questions',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('questions_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('question_text', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='questions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('options',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('option_text', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name='options_question_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='options_pkey')
    )
    # ### end Alembic commands ###
