"""Updated schema

Revision ID: 63544f721c42
Revises: f4f34d5a5045
Create Date: 2025-04-04 19:00:51.868351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63544f721c42'
down_revision: Union[str, None] = 'f4f34d5a5045'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('events', 'requested_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'requested_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('events', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
