"""Updated schema for feedback

Revision ID: ad12a3f18a4c
Revises: f7fb1bb24aee
Create Date: 2025-04-09 15:24:52.528957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad12a3f18a4c'
down_revision: Union[str, None] = 'f7fb1bb24aee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_feedback_id', table_name='feedback')
    op.drop_table('feedback')
    op.drop_index('ix_user_responses_id', table_name='user_responses')
    op.drop_table('user_responses')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_responses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('selected_option', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name='user_responses_question_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], name='user_responses_user_profile_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_responses_pkey')
    )
    op.create_index('ix_user_responses_id', 'user_responses', ['id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('giver_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('receiver_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('feedback_text', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['giver_user_id'], ['user_profiles.id'], name='feedback_giver_user_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receiver_user_id'], ['user_profiles.id'], name='feedback_receiver_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='feedback_pkey')
    )
    op.create_index('ix_feedback_id', 'feedback', ['id'], unique=False)
    # ### end Alembic commands ###
