"""Updated schema for qustion-option

Revision ID: f7fb1bb24aee
Revises: eb4c613392a7
Create Date: 2025-04-07 15:51:30.955369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7fb1bb24aee'
down_revision: Union[str, None] = 'eb4c613392a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_responses_id', table_name='user_responses')
    op.drop_table('user_responses')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_responses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('selected_option', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name='user_responses_question_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], name='user_responses_user_profile_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_responses_pkey')
    )
    op.create_index('ix_user_responses_id', 'user_responses', ['id'], unique=False)
    # ### end Alembic commands ###
